# Detekt configuration for LojaSocialIPCA_API
# More info: https://detekt.dev/docs/introduction/configurations

build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    complexity: 2
    LongParameterList: 1
    LongMethod: 1
    LargeClass: 1
    Style: 0
    comments: 0

output-reports:
  active: true
  exclude:
    - TxtReport
    - SarifReport

comments:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: false
  EndOfLineComment:
    active: false
  OutdatedDocComment:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  CognitiveComplexMethod:
    active: true
    threshold: 15
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 70
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
    ignoreDefaultParameters: false
    ignoreDataClasses: true
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 4
  NestedScopeFunctions:
    active: false
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: true
    thresholdInClasses: 15
    thresholdInInterfaces: 11
    thresholdInObjects: 15
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  RedundantSuspendModifier:
    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: true
  EmptyBlock:
    active: true
    allowedExceptions: ['IgnoredException']
  EmptyClassBlock:
    active: false
  EmptyFunctionBlock:
    active: false
  EmptyIfBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyTryBlock:
    active: true
  EmptyCatchBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptySecondaryConstructor:
    active: false

exceptions:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  ExceptionRaisedInUnexpectedLocation:
    active: false
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable

formatting:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  AnnotationOnSeparateLine:
    active: true
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: false
  ChainMethodContinuation:
    active: false
  CommentSpacing:
    active: true
  Filename:
    active: true
  FinalNewline:
    active: true
    insertFinalNewline: true
  FunctionReturnTypeSpacing:
    active: true
  FunctionStartOfBodySpacing:
    active: false
  FunKeywordSpacing:
    active: true
  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
  ModifierListSpacing:
    active: true
  MultilineIfThenBracing:
    active: false
  MultilineLoopKeywordBracing:
    active: false
  NoBlankLineBeforeRbrace:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: false
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingCommas:
    active: false
  NoTrailingSpaces:
    active: true
  NoWildcardImports:
    active: true
  PackageNaming:
    active: true
    packagePattern: '^[a-z][a-z\d_]*(\.[a-z][a-z\d_]*)*$'
  ParameterListWrapping:
    active: false
  PropertyName:
    active: true
    constantPattern: '[A-Z][A-Z_\d]*'
    propertyPattern: '[a-z][a-zA-Z\d]*'
    privatePropertyPattern: '(_)?[a-z][a-zA-Z\d]*'
  PropertyWrapping:
    active: false
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundRangeOperator:
    active: true
  SpacingBeforeColon:
    active: false
  StringTemplate:
    active: true

naming:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z\d]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z\d]*'
    privateParameterPattern: '[a-z][a-zA-Z\d]*'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][A-Z_\d]*'
  FunctionMaxLength:
    active: false
  FunctionMinLength:
    active: false
  FunctionNaming:
    active: true
    functionPattern: '([a-z][a-zA-Z\d]*)|(`.*`)'
    excludeClassPattern: '$^'
    ignoreOverridden: true
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z\d]*'
    excludeClassPattern: '$^'
    ignoreOverriddenFunctions: true
  InvalidPackageDeclaration:
    active: true
    rootPackage: 'com.ipca'
  LambdaParameterNaming:
    active: false
  MatchingDeclarationName:
    active: true
  MemberNameEqualsClassName:
    active: true
  NoNameShadowing:
    active: false
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Z_\d]*'
    propertyPattern: '[a-z][a-zA-Z\d]*'
    privatePropertyPattern: '(_)?[a-z][a-zA-Z\d]*'
  PackageNaming:
    active: true
    packagePattern: '^[a-z][a-z\d_]*(\.[a-z][a-z\d_]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Z_\d]*'
    propertyPattern: '[a-z][a-zA-Z\d]*'
    privatePropertyPattern: '(_)?[a-z][a-zA-Z\d]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z\d]*'
    privateVariablePattern: '(_)?[a-z][a-zA-Z\d]*'
    excludeClassPattern: '$^'
    ignoreOverridden: true

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: false
  ForEachRange:
    active: true
  ManualRandomBetweenInRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
    forbiddenTypePatterns:
      - 'kotlin.String'
  CastToNullableType:
    active: true
  Deprecation:
    active: false
  DontDowncastCollectionTypes:
    active: false
  DoubleMutabilityForCollection:
    active: true
  DuplicateCaseInWhenExpression:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: false
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: true
  ImplicitUnitReturnType:
    active: false
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: false
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: false
  MissingPackageDeclaration:
    active: false
  MissingWhileKeyword:
    active: true
  NullInsteadOfNotNullAssert:
    active: false
  NullabilityAndPlatformTypes:
    active: false
  PropertyUsedBeforeDeclaration:
    active: false
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnderscoreExpression:
    active: false
  UselessPostfixExpression:
    active: true
  WrongNullCheckInBooleanExpression:
    active: true

style:
  active: true
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  BracesOnIfStatements:
    active: false
  BracesOnWhenStatements:
    active: false
  CanBeNonNullable:
    active: false
  CascadingCallWrapping:
    active: false
  ClassOrdering:
    active: false
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: true
    values:
      - 'TODO:'
      - 'FIXME:'
      - 'STOPSHIP:'
      - 'KLUDGE:'
      - 'XXX:'
      - 'HACK:'
    allowedCommentStartCharacters: []
  ForbiddenImport:
    active: false
  ForbiddenMethodCall:
    active: false
  ForbiddenPublicDataClass:
    active: false
  ForbiddenVoidMethodOverride:
    active: false
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverridableFunction: true
    ignoreActualFunctions: true
    ignoreExpectedFunctions: false
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnumConstants: true
    ignoreRanges: false
    ignoreExtensionFunctions: true
  MandatoryBracesLoops:
    active: false
  MaxChainedCallsOnSameLine:
    active: false
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
  MultilineLambdaItParameter:
    active: false
  MultilineRawStringIndentation:
    active: false
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfStatement:
    active: false
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: false
  ObjectLiteralToLambda:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: false
  PreferToOverPairSyntax:
    active: true
  ProtectedMemberInFinalClass:
    active: false
  RedundantExplicitType:
    active: false
  RedundantHigherOrderMapUsage:
    active: true
  RedundantInnerClassModifier:
    active: true
  RedundantNotNullCheck:
    active: true
  RedundantSuspendModifier:
    active: true
  RedundantVisibilityModifierRule:
    active: false
  SafeCast:
    active: true
  SerialVersionUidInSerializableClass:
    active: false
  SpacingBetweenDeclarations:
    active: true
    linesCount: 1
  ThrowsCount:
    active: true
    max: 2
  TrailingWhitespace:
    active: true
  TrimmedBlocksInFile:
    active: false
  TypeAliasNaming:
    active: false
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: false
  UnnecessaryVariable:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: false
  UseIsEven:
    active: false
  UseLet:
    active: false
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseTestAssertions:
    active: false
  UselessCallOnNotNull:
    active: true
  UselessCompareTo:
    active: true
  UselessLet:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true

verify:
  active: true
  DeprecatedBlockTag:
    active: false
